# Generated by Django 2.2.2 on 2019-06-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=25, unique=True)),
                ('password', models.TextField(max_length=25)),
                ('name', models.TextField(max_length=25)),
                ('age', models.TextField(max_length=25)),
                ('address', models.TextField(max_length=75)),
                ('mobile', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='info',
            fields=[
                ('username', models.TextField(max_length=25, primary_key=True, serialize=False)),
                ('password', models.TextField(max_length=25)),
            ],
        ),
    ]
