# Generated by Django 2.2.2 on 2019-06-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='age',
            field=models.TextField(max_length=3),
        ),
        migrations.AlterField(
            model_name='data',
            name='password',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='data',
            name='username',
            field=models.TextField(max_length=10, unique=True),
        ),
    ]
