# Generated by Django 2.2.2 on 2019-07-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20190701_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='emailid',
        ),
        migrations.RemoveField(
            model_name='data',
            name='id',
        ),
        migrations.AlterField(
            model_name='data',
            name='address',
            field=models.TextField(default='yet to enter', max_length=75),
        ),
        migrations.AlterField(
            model_name='data',
            name='age',
            field=models.TextField(default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='data',
            name='mobile',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='data',
            name='name',
            field=models.TextField(default='yet to enter', max_length=25),
        ),
        migrations.AlterField(
            model_name='data',
            name='username',
            field=models.TextField(primary_key=True, serialize=False, unique=True),
        ),
    ]
