# Generated by Django 2.2.2 on 2019-07-02 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20190702_0511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='address',
        ),
    ]
