# Generated by Django 2.2.2 on 2019-07-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_remove_data_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='age',
            field=models.TextField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='data',
            name='mobile',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='data',
            name='name',
            field=models.TextField(default='', max_length=25),
        ),
    ]
