# Generated by Django 2.2.2 on 2019-07-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20190702_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='mobile',
            field=models.IntegerField(default=0),
        ),
    ]
