# Generated by Django 2.2.2 on 2019-07-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20190702_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='mobile',
            field=models.TextField(default='', max_length=10),
        ),
    ]
