# Generated by Django 2.2.2 on 2019-07-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_auto_20190702_0526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='username',
        ),
        migrations.AddField(
            model_name='data',
            name='age',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='data',
            name='user_id',
            field=models.CharField(default='', max_length=25, primary_key=True, serialize=False),
        ),
    ]
