# Generated by Django 2.2.2 on 2019-07-02 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_auto_20190702_0536'),
    ]

    operations = [
        migrations.DeleteModel(
            name='data',
        ),
    ]
