# Generated by Django 2.2.2 on 2019-06-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pollstr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes1', models.CharField(default='0', max_length=50)),
                ('votes2', models.CharField(default='0', max_length=50)),
                ('votes3', models.CharField(default='0', max_length=50)),
                ('votes4', models.CharField(default='0', max_length=50)),
            ],
        ),
    ]
