# Generated by Django 2.2.2 on 2019-06-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollstr',
            name='order',
            field=models.CharField(default='only', max_length=50),
        ),
    ]
